version: "3.8"

services:
  # api:
  #   container_name: api
  #   build:
  #     context: .
  #     dockerfile: ./apps/messenger-api/Dockerfile
  #   restart: always
  #   ports:
  #     - 4000:4000
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/messenger-web/Dockerfile
    restart: always
    ports:
      - 5173:5173
