services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/messenger-api/Dockerfile
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - postgres
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/messenger-web/Dockerfile
    restart: always
    ports:
      - 5173:5173
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=messenger
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
